name: Deploy Worker

on:
  workflow_dispatch:
  push:

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ (github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main') && 'main' || 'development' }}
    permissions:
      contents: write

    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Deploy with Wrangler
        id: wrangler_deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.114.1"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Write Deployment URL to Summary
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.wrangler_deploy.outputs.deployment-url }}" >> $GITHUB_STEP_SUMMARY
